name: Setup Python
description: 'Set up Python for use in actions by'
inputs:
  python-version:
    description: 'Version range or exact version of a Python version to use, using SemVer version range syntax'
    required: true
    default: '3.x'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    
    - run: python -m pip install --upgrade pip
      shell: sh
    
    - run: pip install -r requirements.txt
      shell: sh
