name: Tests, Build and Deploy to Staging

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.11

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, '3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: pytest hello.py
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: |
          flake8 hello.py
          black --check hello.py

  
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build
        run: echo "This is a mock build."

  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    steps:
      - uses: actions/checkout@v3

      - run: echo "This is a mock deploy to staging."
